name: Latest Blog Posts

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    name: Update this repo's README with latest blog posts
    
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/warengonzaga,https://www.warengonzaga.com/feed/"